### PR TITLE
Add searchbar using list.js, fix non-facebook links and minor style issues

### PR DESCRIPTION
**Pull request by asross**
Here's a quick visual summary of the changes:
hubmap-pr-2

Main questions I have are:
- Is the list functionality (I used [list.js](https://listjs.com/)) sufficient?
- If so, do we want to copy over its javascript (it's pretty lightweight), or keep using the CDN?
- The [underlying google sheet](https://docs.google.com/spreadsheets/d/1ZX3bzLhbnq1MICD_siWDw2hxeP0SGXGoHyuXpzp-rzA) has some issues that should also get resolved; in particular, its "Facebook Group Link" is not always a facebook link for every hub. Is it better to deploy this now or resolve those issues first?
- This is minor, but I think there's a typo in the very first entry ("Hunstville Alabama")... I believe it should be "Huntsville".
- I made the emails `mailto` links, because that makes them a lot easier to copy. Is that ok?

Will see if I can host it on "netlify" for interactive review. You can also just check out this branch and follow the instructions in the README :)

### CODE REVIEW

**Comment by alaurenz** [comment]
@asross This is great. I think listjs is a good solution...I'd say probably good to use a CDN for the library. I ran it using the Python server you setup, super useful. However Im getting a couple issues:
- Basemap is showing up as grey (tiles dont seem to be loading)
- seeing some JS errors in the console (`Uncaught RangeError: out of range source coordinates for image copy` upon load and `hub_map.html:464 Uncaught TypeError: Cannot read property 'classList' of null`upon clicking pins.)
- Also its not working properly in mobile view (you can use Chrome developer tools to simulate mobile). I pushed a commit to this branch to add the viewport line to hub_map.html, but even after that the list doesnt show up on mobile.

**Comment by asross** [comment]
> @asross This is great. I think listjs is a good solution...I'd say probably good to use a CDN for the library. I ran it using the Python server you setup, super useful. However Im getting a couple issues:
> 
> * Basemap is showing up as grey (tiles dont seem to be loading)
> * seeing some JS errors in the console (`Uncaught RangeError: out of range source coordinates for image copy` upon load and `hub_map.html:464 Uncaught TypeError: Cannot read property 'classList' of null`upon clicking pins.)
> * Also its not working properly in mobile view (you can use Chrome developer tools to simulate mobile). I pushed a commit to this branch to add the viewport line to hub_map.html, but even after that the list doesnt show up on mobile.

Awesome, thanks for those comments. Will try to debug!

One thing I'm realizing is that the hub map viewed in standalone mode is actually not equivalent to the hub map as it appears on sunrisemovement.org. In particular, the spacing issues I was noticing when developing locally actually don't appear to be problems on the main site.

I think what I will try to do for this PR instead is:
- to download a static copy of the sunrisemovement.org front page
- replace sunrisemovement.org's hub map with a placeholder
- do a regex replace on the mini-server to swap out the placeholder with the contents of `hub_map.html`
- show that version page (so the hubmap appears in something like its final context)

Hopefully that will resolve all of those issues (and also ensure we don't accidentally introduce any new bugs).

**Comment by asross** [comment]
~~@alaurenz I didn't do a regex swap on the server, but if you copy-paste the contents of `hub_map.html` into the space between the "INSERT HUB MAP" comments in `index.html`, then visit `localhost:8000`, you should be able to view the hub map in something much more like its final context.~~
Update: I created a simple server using Flask and did a regex replace, so downloading flask, running `FLASK_APP=app.py flask run`, then visiting `localhost:5000` should let you view the map more-or-less as it will look in the main site. You can also visit [https://testing-sunrise-webfeats.s3.amazonaws.com/index.html](https://testing-sunrise-webfeats.s3.amazonaws.com/index.html).

I think this fixes all of the mobile and CSS issues.

However, I'm unable to replicate the issues you're having with Basemap tiles and console errors. Could you check if you're still experiencing them / give more details if so?

**Comment by alaurenz** [comment]
This looks great @asross ! Really amazing work. I also tested it on mobile and it seems to be working great. I merged it to master. Can you deploy it on the main Sunrise site? Right now you have to update the code in 2 places:
1) Homepage
2) https://www.sunrisemovement.org/hubs

**Pull request merged**
